version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Uncomment for GPU support (if you have NVIDIA GPU)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  nojs-ai:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./chat_data:/app/data
      - ./logs:/app/logs
    environment:
      - DB_PATH=/app/data/chat.db
      - OLLAMA_URL=http://ollama:11434
    container_name: nojs-ai-assistant
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data: